### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by pol690** [grangier/python-goose#285]
When trying to install, pip install -r requirements.txt rises th following error:

`ERROR: Command errored out with exit status 1:
     command: /home/artemk/Documents/ML_development/ML_dev/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kmx5cyca/beautifulsoup/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kmx5cyca/beautifulsoup/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-kmx5cyca/beautifulsoup/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-kmx5cyca/beautifulsoup/setup.py", line 22
        print "Unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Unit tests have failed!")?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

**Comment by 1a1a11a** [comment]
I think it only supports Python 2

**Comment by pol690** [comment]
Indeed. Thanks! I suppose the solution would be to go to newspaper, which uses goose code, too.
